kind: Deployment
apiVersion: apps/v1
metadata:
  name: smart-igloo-hub-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-igloo-hub-broker
  template:
    metadata:
      labels:
        app: smart-igloo-hub-broker
    spec:
      containers:
        - name: smart-igloo-hub-broker
          image: emqx/emqx-edge
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
            - containerPort: 18083