apiVersion: v1
kind: Service
metadata:
  name: smart-igloo-broker-cluster-ip
  labels:
    app: smart-igloo-hub-broker
spec:
  type: ClusterIP
  ports:
    - port: 1883
      name: mqtt
      protocol: TCP
  selector:
    app: smart-igloo-hub-broker