kind: ConfigMap
apiVersion: v1
metadata:
  name: smart-igloo-broker-cfg-map
data:
  EMQX_LOADED_PLUGINS: "emqx_auth_http,emqx_web_hook"
  EMQX_AUTH__HTTP__AUTH_REQ__URL: "http://{smart_igloo_url}/message-broker/auth"
  EMQX_AUTH__HTTP__AUTH_REQ__METHOD: "post"
  EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT_TYPE: "application/json"
  EMQX_AUTH__HTTP__AUTH_REQ__PARAMS: "client_id=%c,username=%u,password=%P"
  EMQX_WEB__HOOK__URL: "http://{smart_igloo_url}/message-broker/events"
  EMQX_WEB__HOOK__HEADERS__CONTENT_TYPE: "application/json"
  EMQX_WEB__HOOK__BODY__ENCODING_OF_PAYLOAD_FIELD: "plain"
  EMQX_WEB__HOOK__POOL_SIZE: "2"
  EMQX_WEB__HOOK__ENABLE_PIPELINING: "true"
  EMQX_WEB__HOOK__RULE__CLIENT__CONNECT__1: "{\"action\": \"on_client_connect\"}"
  EMQX_WEB__HOOK__RULE__CLIENT__CONNACK__1: "{\"action\": \"on_client_connack\"}"
  EMQX_WEB__HOOK__RULE__CLIENT__CONNECTED__1: "{\"action\": \"on_client_connected\"}"
  EMQX_WEB__HOOK__RULE__CLIENT__DISCONNECTED__1: "{\"action\": \"on_client_disconnected\"}"
  EMQX_WEB__HOOK__RULE__SESSION__TERMINATED__1: "{\"action\": \"on_session_terminated\"}"