apiVersion: v1
kind: Service
metadata:
  name: smart-igloo-broker-lb
  labels:
    app: smart-igloo-hub-broker
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      name: mqtt
    - port: 18083
      name: dashboard
  selector:
    app: smart-igloo-hub-broker

