/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package red.tetracube

class App {

    fun getDeploymentProperties() {
        val dbPassword = getUserInput(
            "${ApplicationGlobal.BLUE} \uD83D\uDD12 Database default password:${ApplicationGlobal.RESET}",
            false
        )
        val deploymentFolder = getUserInput(
            "${ApplicationGlobal.BLUE} \uD83D\uDCC2 Deployment folder where persist data:${ApplicationGlobal.RESET}",
            true
        )
    }

    private fun getUserInput(inputLabel: String, optional: Boolean): String {
        print(inputLabel)
        val input = readLine()!!
        while (input == "" && !optional) {
           return getUserInput(inputLabel, false)
        }
        return input
    }
}

fun main() {
    App().getDeploymentProperties()
}
