apiVersion: v1

kind: PersistentVolume
metadata:
  name: smart-igloo-init-db-pv
  labels:
    type: local
    app: smart-igloo-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: {db_data_path}/docker-entrypoint-initdb.d